services:
  # Container do banco de dados
  db:
    image: mariadb:11
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - harbor_network

  # Container do PHP + FPM
  php:
    image: php:8.2-fpm
    container_name: wp_php
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./wp:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini # se quiser configs customizadas
    networks:
      - harbor_network
    depends_on:
      - db

  # Container do Nginx
  web:
    image: nginx:latest
    container_name: wp_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wp:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - harbor_network
    depends_on:
      - php

  # Opcional: phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - harbor_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  harbor_network:
    driver: bridge
